name: Build siakhooi/bukusaga

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      test-image:
        image: siakhooi/tionghua:latest
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v4
      - run: wget -P ./build -nH --mirror --convert-links --adjust-extension --page-requisites --no-parent http://localhost:8080
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
